### ISSUE TITLE
Steam Crashing.

### ISSUE THREAD

**Issue by songww** [Supreeeme/xwayland-satellite#10]
logs of satelite:

> ➜  RUST_LOG=debug xwayland-satellite
>  2024-05-15T13:53:19.715Z DEBUG xwayland_satellite::server::dispatch > new surface with key ObjectKey(9v1)
>  2024-05-15T13:53:19.719Z INFO  xwayland_satellite                   > Connected to Xwayland on :0
>  2024-05-15T13:53:19.719Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 35, parent: Window { res_id: 977 }, window: Window { res_id: 2097157 }, x: 0, y: 0, width: 1, height: 1, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:19.726Z INFO  xwayland_process                     > The XKEYBOARDkeymap compiler (xkbcomp) reports:
>  2024-05-15T13:53:19.726Z INFO  xwayland_process                     > > Warning:      Unsupported maximum keycode 708, clipping.
>  2024-05-15T13:53:19.726Z INFO  xwayland_process                     > >      X11 cannot support keycodes above 255.
>  2024-05-15T13:53:19.726Z INFO  xwayland_process                     > Errors from xkbcomp are not fatal to the X server
>  2024-05-15T13:53:24.393Z INFO  xwayland_process                     > The XKEYBOARDkeymap compiler (xkbcomp) reports:
>  2024-05-15T13:53:24.393Z INFO  xwayland_process                     > > Warning:      Unsupported maximum keycode 708, clipping.
>  2024-05-15T13:53:24.393Z INFO  xwayland_process                     > >      X11 cannot support keycodes above 255.
>  2024-05-15T13:53:24.394Z INFO  xwayland_process                     > Errors from xkbcomp are not fatal to the X server
>  2024-05-15T13:53:29.444Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 48, parent: Window { res_id: 977 }, window: Window { res_id: 4194306 }, x: 0, y: 0, width: 400, height: 129, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:29.445Z DEBUG xwayland_satellite::xstate           > changed property Lat1("STEAM_BIGPICTURE") for Window { res_id: 4194306 }
>  2024-05-15T13:53:29.445Z DEBUG xwayland_satellite::xstate           > Window { res_id: 4194306 } named:
>  2024-05-15T13:53:29.447Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_PROTOCOLS") for Window { res_id: 4194306 }
>  2024-05-15T13:53:29.544Z DEBUG xwayland_satellite::xstate           > Window { res_id: 4194306 } named:
>  2024-05-15T13:53:30.050Z DEBUG xwayland_satellite::xstate           > Window { res_id: 4194306 } request: X | Y
>  2024-05-15T13:53:30.050Z DEBUG xwayland_satellite::server           > setting Window { res_id: 4194306 } hints WmNormalHints { min_size: Some(WinSize { width: 400, height: 129 }), max_size: Some(WinSize { width: 400, height: 129 }) }
>  2024-05-15T13:53:30.050Z DEBUG xwayland_satellite::xstate           > requested to map Window { res_id: 4194306 }
>  2024-05-15T13:53:30.097Z DEBUG xwayland_satellite::server           > mapping Window { res_id: 4194306 }
>  2024-05-15T13:53:30.098Z DEBUG xwayland_satellite::server::dispatch > new surface with key ObjectKey(14v1)
>  2024-05-15T13:53:30.098Z DEBUG xwayland_satellite::server::dispatch > associate surface 22 with window Window { res_id: 4194306 }
>  2024-05-15T13:53:30.098Z DEBUG xwayland_satellite::server           > creating toplevel for Window { res_id: 4194306 }
>  2024-05-15T13:53:30.098Z DEBUG xwayland_satellite::server::event    > configuring toplevel 852x1027, [5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0]
>  2024-05-15T13:53:30.098Z DEBUG xwayland_satellite::server::event    > configuring Window { res_id: 4194306 }: 0x0, 852x1027
>  2024-05-15T13:53:30.100Z DEBUG xwayland_satellite::server::event    > configuring toplevel 400x129, [5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0, 4, 0, 0, 0]
>  2024-05-15T13:53:30.100Z DEBUG xwayland_satellite::server::event    > configuring Window { res_id: 4194306 }: 0x0, 400x129
>  2024-05-15T13:53:30.102Z DEBUG xwayland_satellite::server           > focusing window Window { res_id: 4194306 }
>  2024-05-15T13:53:30.781Z DEBUG xwayland_satellite::server           > unmapping Window { res_id: 4194306 }
>  2024-05-15T13:53:30.781Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 4194306 }
>  2024-05-15T13:53:30.802Z INFO  xwayland_process                     > The XKEYBOARDkeymap compiler (xkbcomp) reports:
>  2024-05-15T13:53:30.802Z INFO  xwayland_process                     > > Warning:      Unsupported maximum keycode 708, clipping.
>  2024-05-15T13:53:30.802Z INFO  xwayland_process                     > >      X11 cannot support keycodes above 255.
>  2024-05-15T13:53:30.804Z INFO  xwayland_process                     > Errors from xkbcomp are not fatal to the X server
>  2024-05-15T13:53:30.906Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 68, parent: Window { res_id: 977 }, window: Window { res_id: 6291457 }, x: 10, y: 10, width: 10, height: 10, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:30.906Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_COMMAND") for Window { res_id: 6291457 }
>  2024-05-15T13:53:30.906Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_CLIENT_MACHINE") for Window { res_id: 6291457 }
>  2024-05-15T13:53:30.906Z DEBUG xwayland_satellite::xstate           > Window { res_id: 6291457 } class: "Steam"
>  2024-05-15T13:53:30.906Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_LOCALE_NAME") for Window { res_id: 6291457 }
>  2024-05-15T13:53:30.906Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_PID") for Window { res_id: 6291457 }
>  2024-05-15T13:53:30.981Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 75, parent: Window { res_id: 977 }, window: Window { res_id: 8388610 }, x: 0, y: 0, width: 1, height: 1, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:30.985Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 8388610 }
>  2024-05-15T13:53:31.164Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 77, parent: Window { res_id: 977 }, window: Window { res_id: 10485762 }, x: 0, y: 0, width: 1, height: 1, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:31.168Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 10485762 }
>  2024-05-15T13:53:31.304Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 79, parent: Window { res_id: 977 }, window: Window { res_id: 4194309 }, x: 0, y: 0, width: 64, height: 24, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:31.304Z DEBUG xwayland_satellite::server           > setting Window { res_id: 4194309 } hints WmNormalHints { min_size: Some(WinSize { width: 0, height: 0 }), max_size: None }
>  2024-05-15T13:53:31.304Z DEBUG xwayland_satellite::xstate           > Window { res_id: 4194309 } class: "Steam"
>  2024-05-15T13:53:31.305Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_ICON") for Window { res_id: 4194309 }
>  2024-05-15T13:53:31.305Z DEBUG xwayland_satellite::xstate           > wm hints: WmHints { input: None, window_group: None }
>  2024-05-15T13:53:31.305Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_PROTOCOLS") for Window { res_id: 4194309 }
>  2024-05-15T13:53:31.712Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 86, parent: Window { res_id: 977 }, window: Window { res_id: 16777218 }, x: 0, y: 0, width: 32, height: 32, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:31.721Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 16777218 }
>  2024-05-15T13:53:31.721Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 88, parent: Window { res_id: 977 }, window: Window { res_id: 16777224 }, x: 2864, y: 524, width: 32, height: 32, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:31.721Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_TRANSIENT_FOR") for Window { res_id: 16777224 }
>  2024-05-15T13:53:31.721Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_CLIENT_MACHINE") for Window { res_id: 16777224 }
>  2024-05-15T13:53:31.721Z DEBUG xwayland_satellite::server           > setting Window { res_id: 16777224 } hints WmNormalHints { min_size: Some(WinSize { width: 32, height: 32 }), max_size: Some(WinSize { width: 32, height: 32 }) }
>  2024-05-15T13:53:31.721Z DEBUG xwayland_satellite::xstate           > wm hints: WmHints { input: None, window_group: Some(Window { res_id: 1059185648 }) }
>  2024-05-15T13:53:31.721Z DEBUG xwayland_satellite::xstate           > Window { res_id: 16777224 } class: "gldriverquery"
>  2024-05-15T13:53:31.721Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_LOCALE_NAME") for Window { res_id: 16777224 }
>  2024-05-15T13:53:31.721Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_PID") for Window { res_id: 16777224 }
>  2024-05-15T13:53:31.722Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_WINDOW_TYPE") for Window { res_id: 16777224 }
>  2024-05-15T13:53:31.722Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_BYPASS_COMPOSITOR") for Window { res_id: 16777224 }
>  2024-05-15T13:53:31.722Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_PROTOCOLS") for Window { res_id: 16777224 }
>  2024-05-15T13:53:31.722Z DEBUG xwayland_satellite::xstate           > Window { res_id: 16777224 } named: OpenGL 4.5
>  2024-05-15T13:53:31.722Z DEBUG xwayland_satellite::xstate           > Window { res_id: 16777224 } named: OpenGL 4.5
>  2024-05-15T13:53:31.722Z DEBUG xwayland_satellite::xstate           > changed property Lat1("XdndAware") for Window { res_id: 16777224 }
>  2024-05-15T13:53:31.739Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_VARIABLE_REFRESH") for Window { res_id: 16777224 }
>  2024-05-15T13:53:31.740Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 16777224 }
>  2024-05-15T13:53:31.780Z DEBUG xwayland_satellite::server::dispatch > deleting key:ObjectKey(14v1)
>  2024-05-15T13:53:32.381Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 104, parent: Window { res_id:977 }, window: Window { res_id: 16777218 }, x: 0, y: 0, width: 32, height: 32, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:32.389Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 16777218 }
>  2024-05-15T13:53:32.390Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 106, parent: Window { res_id:977 }, window: Window { res_id: 16777224 }, x: 2864, y: 524, width: 32, height: 32, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:32.390Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_LOCALE_NAME") for Window { res_id: 16777224 }
>  2024-05-15T13:53:32.390Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_PID") for Window { res_id: 16777224 }
>  2024-05-15T13:53:32.390Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_WINDOW_TYPE") for Window { res_id: 16777224 }
>  2024-05-15T13:53:32.390Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_BYPASS_COMPOSITOR") for Window { res_id: 16777224 }
>  2024-05-15T13:53:32.390Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_PROTOCOLS") for Window { res_id: 16777224 }
>  2024-05-15T13:53:32.390Z DEBUG xwayland_satellite::xstate           > Window { res_id: 16777224 } named: OpenGL 4.5
>  2024-05-15T13:53:32.390Z DEBUG xwayland_satellite::xstate           > Window { res_id: 16777224 } named: OpenGL 4.5
>  2024-05-15T13:53:32.390Z DEBUG xwayland_satellite::xstate           > changed property Lat1("XdndAware") for Window { res_id: 16777224 }
>  2024-05-15T13:53:32.405Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_VARIABLE_REFRESH") for Window { res_id: 16777224 }
>  2024-05-15T13:53:32.407Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 16777224 }
>  2024-05-15T13:53:35.780Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 117, parent: Window { res_id:977 }, window: Window { res_id: 16777216 }, x: -100, y: -100, width: 10, height: 10,border_width: 0, override_redirect: true, pad: 1 }
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 119, parent: Window { res_id:977 }, window: Window { res_id: 18874369 }, x: 10, y: 10, width: 10, height: 10, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > Window { res_id: 18874369 } named: steamwebhelper
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > Window { res_id: 18874369 } named: steamwebhelper
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::server           > skipping setting window name to WmName("steamwebhelper") because a _NET_WM_NAME title is already set
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_ICON_NAME") for Window { res_id: 18874369 }
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_ICON_NAME") for Window { res_id: 18874369 }
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_PROTOCOLS") for Window { res_id: 18874369 }
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::server           > setting Window { res_id: 18874369 } hints WmNormalHints { min_size: None, max_size: None }
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_CLIENT_MACHINE") for Window { res_id: 18874369 }
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_LOCALE_NAME") for Window { res_id: 18874369 }
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_PID") for Window { res_id: 18874369 }
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_CLIENT_LEADER") for Window { res_id: 18874369 }
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_COMMAND") for Window { res_id: 18874369 }
>  2024-05-15T13:53:35.872Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_CLIENT_MACHINE") for Window { res_id: 18874369 }
>  2024-05-15T13:53:35.873Z DEBUG xwayland_satellite::xstate           > Window { res_id: 18874369 } class: "Steamwebhelper"
>  2024-05-15T13:53:35.873Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_LOCALE_NAME") for Window { res_id: 18874369 }
>  2024-05-15T13:53:35.873Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_PID") for Window { res_id: 18874369 }
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 136, parent: Window { res_id:977 }, window: Window { res_id: 18874371 }, x: 0, y: 0, width: 200, height: 200, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::xstate           > Window { res_id: 18874369 } named: steamwebhelper
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::xstate           > Window { res_id: 18874369 } named: steamwebhelper
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::server           > skipping setting window name to WmName("steamwebhelper") because a _NET_WM_NAME title is already set
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::server           > setting Window { res_id: 18874371 } hints WmNormalHints { min_size: None, max_size: None }
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_CLIENT_MACHINE") for Window { res_id: 18874371 }
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_LOCALE_NAME") for Window { res_id: 18874371 }
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_PID") for Window { res_id: 18874371 }
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_CLIENT_LEADER") for Window { res_id: 18874371 }
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_USER_TIME_WINDOW") for Window { res_id: 18874371 }
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_SYNC_REQUEST_COUNTER") for Window { res_id: 18874371 }
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_WINDOW_TYPE") for Window { res_id: 18874371 }
>  2024-05-15T13:53:35.897Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_OPAQUE_REGION") for Window { res_id: 18874371 }
>  2024-05-15T13:53:36.155Z DEBUG xwayland_satellite::xstate           > changed property Lat1("XdndAware") for Window { res_id: 18874371 }
>  2024-05-15T13:53:36.293Z DEBUG xwayland_satellite::xstate           > Window { res_id: 4194309 } request: X | Y | WIDTH | HEIGHT
>  2024-05-15T13:53:36.298Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_VARIABLE_REFRESH") for Window { res_id: 4194309 }
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 155, parent: Window { res_id:977 }, window: Window { res_id: 31457322 }, x: 2527, y: 320, width: 705, height: 440, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_MOTIF_WM_HINTS") for Window { res_id: 31457322 }
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_CLIENT_MACHINE") for Window { res_id: 31457322 }
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::server           > setting Window { res_id: 31457322 } hints WmNormalHints { min_size: Some(WinSize { width: 705, height: 440 }), max_size: Some(WinSize { width: 705, height: 440 }) }
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > wm hints: WmHints { input: None, window_group: Some(Window { res_id: 3153259063 }) }
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457322 } class: "steam"
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_LOCALE_NAME") for Window { res_id: 31457322 }
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_PID") for Window { res_id: 31457322 }
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_WINDOW_TYPE") for Window { res_id: 31457322 }
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > changed property Lat1("WM_PROTOCOLS") for Window { res_id: 31457322 }
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457322 } named:
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457322 } named: SteamWebhelper
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > changed property Lat1("XdndAware") for Window { res_id: 31457322 }
>  2024-05-15T13:53:37.579Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 31457322 }
>  2024-05-15T13:53:37.644Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 169, parent: Window { res_id:977 }, window: Window { res_id: 31457324 }, x: 0, y: 0, width: 32, height: 32, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:37.650Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 31457324 }
>  2024-05-15T13:53:37.650Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 171, parent: Window { res_id:977 }, window: Window { res_id: 31457330 }, x: 2527, y: 320, width: 705, height: 440, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:37.650Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } named:
>  2024-05-15T13:53:37.650Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } named: SteamWebhelper
>  2024-05-15T13:53:37.650Z DEBUG xwayland_satellite::xstate           > changed property Lat1("XdndAware") for Window { res_id: 31457330 }
>  2024-05-15T13:53:37.664Z DEBUG xwayland_satellite::server           > setting Window { res_id: 31457330 } hints WmNormalHints { min_size: Some(WinSize { width: 705, height: 440 }), max_size: Some(WinSize { width: 705, height: 440 }) }
>  2024-05-15T13:53:37.664Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } request: WIDTH | HEIGHT
>  2024-05-15T13:53:37.664Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } request: X | Y
>  2024-05-15T13:53:37.664Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } request: STACK_MODE
>  2024-05-15T13:53:37.664Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } request: X | Y
>  2024-05-15T13:53:37.664Z DEBUG xwayland_satellite::xstate           > changed property Lat1("STEAM_GAME") for Window { res_id: 31457330 }
>  2024-05-15T13:53:37.664Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_ICON") for Window { res_id: 31457330 }
>  2024-05-15T13:53:37.668Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 187, parent: Window { res_id:977 }, window: Window { res_id: 16777224 }, x: 0, y: 0, width: 1, height: 1, border_width: 0, override_redirect: true, pad: 1 }
>  2024-05-15T13:53:37.668Z DEBUG xwayland_satellite::xstate           > changed property Lat1("CHROMIUM_TIMESTAMP") for Window { res_id: 16777224 }
>  2024-05-15T13:53:37.669Z DEBUG xwayland_satellite::xstate           > changed property Lat1("XdndProxy") for Window { res_id: 31457330 }
>  2024-05-15T13:53:37.669Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } request: WIDTH | HEIGHT
>  2024-05-15T13:53:37.670Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } request: X | Y
>  2024-05-15T13:53:37.670Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } request: STACK_MODE
>  2024-05-15T13:53:37.674Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } named:
>  2024-05-15T13:53:37.674Z DEBUG xwayland_satellite::server           > skipping setting window name to WmName("") because a _NET_WM_NAME title is already set
>  2024-05-15T13:53:37.674Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } named: undefined
>  2024-05-15T13:53:37.674Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } named:
>  2024-05-15T13:53:37.674Z DEBUG xwayland_satellite::server           > skipping setting window name to WmName("") because a _NET_WM_NAME title is already set
>  2024-05-15T13:53:37.674Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } named: undefined
>  2024-05-15T13:53:37.676Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } named:
>  2024-05-15T13:53:37.676Z DEBUG xwayland_satellite::server           > skipping setting window name to WmName("") because a _NET_WM_NAME title is already set
>  2024-05-15T13:53:37.676Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } named: 登录 Steam
>  2024-05-15T13:53:37.752Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } request: STACK_MODE
>  2024-05-15T13:53:37.752Z DEBUG xwayland_satellite::xstate           > requested to map Window { res_id: 31457330 }
>  2024-05-15T13:53:37.757Z DEBUG xwayland_satellite::server           > mapping Window { res_id: 31457330 }
>  2024-05-15T13:53:37.757Z DEBUG xwayland_satellite::server::dispatch > new surface with key ObjectKey(17v3)
>  2024-05-15T13:53:37.757Z DEBUG xwayland_satellite::server::dispatch > associate surface 33 with window Window { res_id: 31457330 }
>  2024-05-15T13:53:37.757Z DEBUG xwayland_satellite::server           > creating toplevel for Window { res_id: 31457330 }
>  2024-05-15T13:53:37.757Z DEBUG xwayland_satellite::server::event    > configuring toplevel 852x1027, [5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0]
>  2024-05-15T13:53:37.757Z DEBUG xwayland_satellite::server::event    > configuring Window { res_id: 31457330 }: 0x0, 852x1027
>  2024-05-15T13:53:37.766Z DEBUG xwayland_satellite::server::event    > configuring toplevel 705x440, [5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0, 4, 0, 0, 0]
>  2024-05-15T13:53:37.766Z DEBUG xwayland_satellite::server::event    > configuring Window { res_id: 31457330 }: 0x0, 705x440
>  2024-05-15T13:53:37.767Z DEBUG xwayland_satellite::server           > focusing window Window { res_id: 31457330 }
>  2024-05-15T13:53:37.768Z WARN  xwayland_satellite::xstate           > unrecognized message: Atom { res_id: 251 }
>  2024-05-15T13:53:37.768Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457330 } request: STACK_MODE
>  2024-05-15T13:53:37.768Z WARN  xwayland_satellite::xstate           > unrecognized message: Atom { res_id: 251 }
>  2024-05-15T13:53:41.210Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 221, parent: Window { res_id:977 }, window: Window { res_id: 31457336 }, x: 0, y: 0, width: 2519, height: 1419, border_width: 0, override_redirect: false, pad: 1 }
>  2024-05-15T13:53:41.211Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457336 } named:
>  2024-05-15T13:53:41.211Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457336 } named: SteamWebhelper
>  2024-05-15T13:53:41.211Z DEBUG xwayland_satellite::xstate           > changed property Lat1("XdndAware") for Window { res_id: 31457336 }
>  2024-05-15T13:53:41.218Z DEBUG xwayland_satellite::xstate           > changed property Lat1("STEAM_GAME") for Window { res_id: 31457336 }
>  2024-05-15T13:53:41.218Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_NET_WM_ICON") for Window { res_id: 31457336 }
>  2024-05-15T13:53:41.218Z DEBUG xwayland_satellite::xstate           > changed property Lat1("_VARIABLE_REFRESH") for Window { res_id: 31457336 }
>  2024-05-15T13:53:41.218Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457336 } request: WIDTH | HEIGHT
>  2024-05-15T13:53:41.218Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457336 } request: WIDTH | HEIGHT
>  2024-05-15T13:53:41.220Z DEBUG xwayland_satellite::xstate           > changed property Lat1("CHROMIUM_TIMESTAMP") for Window { res_id: 16777224 }
>  2024-05-15T13:53:41.221Z DEBUG xwayland_satellite::xstate           > changed property Lat1("CHROMIUM_TIMESTAMP") for Window { res_id: 16777224 }
>  2024-05-15T13:53:41.222Z DEBUG xwayland_satellite::xstate           > changed property Lat1("XdndProxy") for Window { res_id: 31457336 }
>  2024-05-15T13:53:41.223Z DEBUG xwayland_satellite::server           > setting Window { res_id: 31457336 } hints WmNormalHints { min_size: Some(WinSize { width: 1010, height: 600 }), max_size: None }
>  2024-05-15T13:53:41.223Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457336 } request: WIDTH | HEIGHT
>  2024-05-15T13:53:41.228Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457336 } named:
>  2024-05-15T13:53:41.228Z DEBUG xwayland_satellite::server           > skipping setting window name to WmName("") because a _NET_WM_NAME title is already set
>  2024-05-15T13:53:41.228Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457336 } named: about:blank?createflags=274&minwidth=1010&minheight=600&pid=0&browser=-1&browserType=4&restoredetails=1&x=0&y=0&w=2519&h=1419&useragent=Valve Steam Client
>  2024-05-15T13:53:41.228Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457336 } named:
>  2024-05-15T13:53:41.228Z DEBUG xwayland_satellite::server           > skipping setting window name to WmName("") because a _NET_WM_NAME title is already set
>  2024-05-15T13:53:41.228Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457336 } named: undefined
>  2024-05-15T13:53:41.229Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457336 } named:
>  2024-05-15T13:53:41.229Z DEBUG xwayland_satellite::server           > skipping setting window name to WmName("") because a _NET_WM_NAME title is already set
>  2024-05-15T13:53:41.230Z DEBUG xwayland_satellite::xstate           > Window { res_id: 31457336 } named: Steam
>  2024-05-15T13:53:41.288Z WARN  xwayland_satellite::xstate           > unhandled event: X(ReparentNotify(ReparentNotifyEvent { response_type: 21, pad: 1, sequence: 245, event: Window { res_id: 977 }, window: Window { res_id: 16777223 }, parent: Window { res_id: 977 }, x: 0, y: 0, override_redirect: true, pad: 3 }))
>  2024-05-15T13:53:41.288Z DEBUG xwayland_satellite::server           > mapping Window { res_id: 16777223 }
> thread 'main' panicked at satellite/src/server/mod.rs:591:52:
> called `Option::unwrap()` on a `None` value
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

logs of steam:

> ➜ DISPLAY=:0 steam
> steam.sh[74959]: Running Steam on kylin V10 64-bit
> steam.sh[74959]: STEAM_RUNTIME is enabled automatically
> setup.sh[75094]: Steam runtime environment up-to-date!
> steam.sh[74959]: Steam client's requirements are satisfied
> WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> [2024-05-15 21:53:29] Startup - updater built May 13 2024 21:00:30
> [2024-05-15 21:53:29] Startup - Steam Client launched with: '/home/songww/.steam/debian-installation/ubuntu12_32/steam'
> 05/15 21:53:29 minidumps folder is set to /tmp/dumps
> 05/15 21:53:29 Init: Installing breakpad exception handler for appid(steam)/version(1715635533)/tid(75155)
> Looks like steam didn't shutdown cleanly, scheduling immediate update check
> [2024-05-15 21:53:29] Loading cached metrics from disk (/home/songww/.steam/debian-installation/package/steam_client_metrics.bin)
> [2024-05-15 21:53:29] Using the following download hosts for Public, Realm steamglobal
> [2024-05-15 21:53:29] 1. https://media.st.dl.eccdnx.com, /client/, Realm 'steamglobal', weight was 100000, source = 'update_hosts_cached.vdf'
> [2024-05-15 21:53:29] 2. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
> [2024-05-15 21:53:29] 3. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
> [2024-05-15 21:53:29] 4. https://cdn.steamstatic.com, /client/, Realm 'steamglobal',weight was 1, source = 'baked in'
> [2024-05-15 21:53:29] Checking for update on startup
> [2024-05-15 21:53:29] 正在检查可用更新...
> [2024-05-15 21:53:29] Downloading manifest: https://media.st.dl.eccdnx.com/client/steam_client_ubuntu12
> [2024-05-15 21:53:29] Manifest download: send request
> [2024-05-15 21:53:29] Manifest download: waiting for download to finish
> [2024-05-15 21:53:30] Manifest download: finished
> [2024-05-15 21:53:30] Download skipped: /client/steam_client_ubuntu12 version 1715635533, installed version 1715635533, existing pending version 0
> [2024-05-15 21:53:30] Nothing to do
> [2024-05-15 21:53:30] 正在验证安装...
> [2024-05-15 21:53:30] Performing checksum verification of executable files
> [2024-05-15 21:53:30] Verification complete
> UpdateUI: skip show logo
> Steam logging initialized: directory: /home/songww/.steam/debian-installation/logs
> 
> XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe6b4c6b0
> XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe6b4af70
> steamwebhelper.sh[75195]: === 2024年 05月 15日 星期三 21:53:31 CST ===
> steamwebhelper.sh[75195]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/songww/.steam/debian-installation/ubuntu12_64/steam-runtime-sniper
> CAppInfoCacheReadFromDiskThread took 28 milliseconds to initialize
> Steam Runtime Launch Service: starting steam-runtime-launcher-service
> Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 75340
> bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
> BRefreshApplicationsInLibrary 1: 0ms

version of xwayland-satellite: commit 7976e3ad3716cdbcbee052c2b019fe67accab76b
compositer: niri with commit 55e550262dcde29b0e0332e257008029b146a97f
os: debian sid latest

**Comment by Supreeeme** [comment]
Does this crash happen consistently or only occasionally?

**Comment by songww** [comment]
It always crashes when jumping to the main steam screen after a successful login.

**Comment by Supreeeme** [comment]
Can't reproduce this with steam but I am able to reproduce it in a test. Seems to be related to subwindows, satellite does not appear to get notifications for windows created that aren't parented to the root window. Will investigate more.

**Comment by Supreeeme** [comment]
I think this should be fixed now, feel free to repopen (with logs!) if not.

**Comment by songww** [comment]
It still crashed.
**Logs of xwayland-satellite:**

> …xwayland-satellite on  main is  v0.2.0 via  v1.80.0-nightly took 1m8s [13:33:34]
> ✗  RUST_BACKTRACE=1 ./target/release/xwayland-satellite
>  2024-05-18T05:34:02.411Z INFO  xwayland_satellite > Connected to Xwayland on :0
>  2024-05-18T05:34:02.418Z INFO  xwayland_process   > The XKEYBOARD keymap compiler (xkbcomp) reports:
>  2024-05-18T05:34:02.418Z INFO  xwayland_process   > > Warning:          Unsupportedmaximum keycode 708, clipping.
>  2024-05-18T05:34:02.418Z INFO  xwayland_process   > >                   X11 cannot support keycodes above 255.
>  2024-05-18T05:34:02.419Z INFO  xwayland_process   > Errors from xkbcomp are not fatal to the X server
>  2024-05-18T05:34:03.525Z INFO  xwayland_process   > The XKEYBOARD keymap compiler (xkbcomp) reports:
>  2024-05-18T05:34:03.525Z INFO  xwayland_process   > > Warning:          Unsupportedmaximum keycode 708, clipping.
>  2024-05-18T05:34:03.525Z INFO  xwayland_process   > >                   X11 cannot support keycodes above 255.
>  2024-05-18T05:34:03.526Z INFO  xwayland_process   > Errors from xkbcomp are not fatal to the X server
>  2024-05-18T05:34:08.535Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
>  2024-05-18T05:34:09.319Z INFO  xwayland_process                     > The XKEYBOARDkeymap compiler (xkbcomp) reports:
>  2024-05-18T05:34:09.319Z INFO  xwayland_process                     > > Warning:      Unsupported maximum keycode 708, clipping.
>  2024-05-18T05:34:09.319Z INFO  xwayland_process                     > >      X11 cannot support keycodes above 255.
>  2024-05-18T05:34:09.321Z INFO  xwayland_process                     > Errors from xkbcomp are not fatal to the X server
>  2024-05-18T05:34:17.134Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
>  2024-05-18T05:34:17.134Z WARN  xwayland_satellite::xstate           > unrecognized message: Atom { res_id: 251 }
>  2024-05-18T05:34:17.134Z WARN  xwayland_satellite::xstate           > unrecognized message: Atom { res_id: 251 }
>  2024-05-18T05:34:26.957Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
>  2024-05-18T05:34:26.957Z WARN  xwayland_satellite::server::dispatch > unhandled wlcompositor request: CreateRegion { id: New { id: WlRegion { id: ObjectId(wl_region@54[0], 800), version: 4, data: Some(Any { .. }), handle: WeakHandle { handle: WeakInnerHandle[rs] { .. } } } } }
> thread 'main' panicked at /home/songww/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/wayland-backend-0.3.3/src/rs/server_impl/common_poll.rs:259:37:
> Callback creating object wl_region@54[0] did not provide any object data.
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: wayland_backend::rs::server_impl::common_poll::InnerBackend<D>::dispatch_all_clients
>    3: xwayland_satellite::main
>    4: xwayland_satellite::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Logs of steam:**

> …xwayland-satellite on  main is  v0.2.0 via  v1.80.0-nightly took 1m1s [13:33:34]
> ➜ DISPLAY=:0 steam
> steam.sh[28550]: Running Steam on kylin V10 64-bit
> steam.sh[28550]: STEAM_RUNTIME is enabled automatically
> setup.sh[28685]: Steam runtime environment up-to-date!
> steam.sh[28550]: Steam client's requirements are satisfied
> WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> [2024-05-18 13:34:07] Startup - updater built May 16 2024 20:10:34
> [2024-05-18 13:34:07] Startup - Steam Client launched with: '/home/songww/.steam/debian-installation/ubuntu12_32/steam'
> 05/18 13:34:07 minidumps folder is set to /tmp/dumps
> 05/18 13:34:07 Init: Installing breakpad exception handler for appid(steam)/version(1715891371)/tid(28745)
> Looks like steam didn't shutdown cleanly, scheduling immediate update check
> [2024-05-18 13:34:07] Loading cached metrics from disk (/home/songww/.steam/debian-installation/package/steam_client_metrics.bin)
> [2024-05-18 13:34:07] Using the following download hosts for Public, Realm steamglobal
> [2024-05-18 13:34:07] 1. https://media.st.dl.eccdnx.com, /client/, Realm 'steamglobal', weight was 100000, source = 'update_hosts_cached.vdf'
> [2024-05-18 13:34:07] 2. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
> [2024-05-18 13:34:07] 3. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
> [2024-05-18 13:34:07] 4. https://cdn.steamstatic.com, /client/, Realm 'steamglobal',weight was 1, source = 'baked in'
> [2024-05-18 13:34:07] Checking for update on startup
> [2024-05-18 13:34:07] 正在检查可用更新...
> [2024-05-18 13:34:07] Downloading manifest: https://media.st.dl.eccdnx.com/client/steam_client_ubuntu12
> [2024-05-18 13:34:07] Manifest download: send request
> [2024-05-18 13:34:07] Manifest download: waiting for download to finish
> [2024-05-18 13:34:08] Manifest download: finished
> [2024-05-18 13:34:08] Download skipped: /client/steam_client_ubuntu12 version 1715891371, installed version 1715891371, existing pending version 0
> [2024-05-18 13:34:08] Nothing to do
> [2024-05-18 13:34:08] 正在验证安装...
> [2024-05-18 13:34:08] Performing checksum verification of executable files
> [2024-05-18 13:34:09] Verification complete
> UpdateUI: skip show logo
> Steam logging initialized: directory: /home/songww/.steam/debian-installation/logs
> 
> XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe79056b0
> XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe7903f70
> steamwebhelper.sh[28785]: === 2024年 05月 18日 星期六 13:34:09 CST ===
> steamwebhelper.sh[28785]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/songww/.steam/debian-installation/ubuntu12_64/steam-runtime-sniper
> CAppInfoCacheReadFromDiskThread took 31 milliseconds to initialize
> Steam Runtime Launch Service: starting steam-runtime-launcher-service
> Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 28925
> bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
> BRefreshApplicationsInLibrary 1: 1ms
> BuildCompleteAppOverviewChange: 180 apps
> RegisterForAppOverview 1: 13ms
> RegisterForAppOverview 2: 13ms

**Comment by Supreeeme** [comment]
I see. This is a different crash though. Didn't see it because I was using Xwayland 23.2.7 and not latest. Seems like an easy enough fix though.

**Comment by Supreeeme** [comment]
Ok, just tested and pushed a fix, should work without issue now.

**Comment by songww** [comment]
It works now, thanks.
