### ISSUE TITLE
Steam Context Menu Popups Are Miss-located

### ISSUE THREAD

**Issue by Twinkie001** [Supreeeme/xwayland-satellite#156]
### Operating System

Arch

### Wayland Compositor

Niri

### Describe the issue.

Steam Context Menu Popups Are Miss-located  and don't spawn at the tooltip.

### Steps to reproduce

Open Steam, hover your mouse over STORE/COMMUNITY/LIBRARY, the the menu will appear separated from the tooltip.

![Image](https://github.com/user-attachments/assets/9510fa9f-d09d-4e98-a3ad-305091176f07)

### Please confirm you have reproduced this on the latest commit.

- [x] I have reproduced this on the latest commit

**Comment by Twinkie001** [comment]
Also, similar to the Reaper problem, floating windows spawn behind the parent window:

![Image](https://github.com/user-attachments/assets/1e131a9c-7cd4-46ef-9101-76350e01ae69)

**Comment by Supreeeme** [comment]
This seems to be a steam bug honestly, I've seen it happen on pure X11 and it usually corrects itself. Are you able to make it happen consistently?

**Comment by Twinkie001** [comment]
Actually it did go away after I switched to niri-git. I'm not sure if it's because of the git version or I did something in addition to that. I tried to run it with xwayland-run but that didn't work. After that I went back to satellite and it went away.

  Btw I also just noticed that  the latest proton Experimental/10 doesn't open full screen. I tried to force it through in Niri's config  but it still stays windowed. I vaguely recall that Xayland on Sway had the same problem a couple of years ago. Proton 9 however opens full screen without any problems.

**Comment by Supreeeme** [comment]
The fullscreen thing was just fixed, see #157.
I'll close this if it's not happening anymore.

**Comment by sudoharun** [comment]
Happening to me now. Just installed Arch + Niri (was on -git on my previous install). Also happens on `niri-git`. I'm also on `xwayland-satellite-git` 0.5.r55.gec9ff64-1.

**Comment by luochen1990** [comment]
![Image](https://github.com/user-attachments/assets/e939baf7-f9f8-4007-b0ba-27f74d5b51e1)

Still have this issue, my mouse is at left-top of the picture, but the context menu is at right-bottom if the picture.

I'm using xwayland-satellite from the flake.nix, here is the xwayland-satellite part of my flake.lock

```nix
    "xwayland-satellite": {
      "inputs": {
        "flake-utils": [
          "flake-utils"
        ],
        "nixpkgs": [
          "nixpkgs-local"
        ],
        "rust-overlay": [
          "rust-overlay"
        ]
      },
      "locked": {
        "lastModified": 1747111562,
        "narHash": "sha256-GAqhWoxaBIk0tgoecZPa8gTHDHxNc0JtlwWHZN2iOOo=",
        "owner": "Supreeeme",
        "repo": "xwayland-satellite",
        "rev": "ec9ff64c1e0cbec42710b580b7c0f759b1694e72",
        "type": "github"
      },
      "original": {
        "owner": "Supreeeme",
        "repo": "xwayland-satellite",
        "type": "github"
      }
    }
```

**Comment by liuhq** [comment]
Same issue for me. But I have found that this issue only occurs with the window opened when steam start. If closs and reopen the window via tray icon (desktop entry acion or something else), it works fine.

**Comment by luochen1990** [comment]
@liuhq Interesting!  this workaround works for me, at least I can use steam now :)

**Comment by FreeFull** [comment]
The issue still happens for me with the latest xwayland-satellite from git. It seems to be tied to the way Steam tries to restore its window position when it starts: If you run steam inside of rootful Xwayland using openbox, and move its window, then the next time you launch it under xwayland-satellite, the popups will be offset exactly by the window position you moved Steam to before.

**Comment by ada-magicat** [comment]
Also happens in mutter git with xwayland-satellite git

**Comment by shumvgolove** [comment]
It seems like the issue is gone after latest Steam update. Can anyone confirm?

upd: Nope, it's back.

**Comment by arc-d3v** [comment]
I did a bit of tests, I have the same issue and I wanted to add a bit of context.
Closing the window and reopen it from tray make the context menu work properly.
It doesn't happen with context menu inside of steam, popup conf, library, store etc.. context menus work properly.
The issue is not going back after closing and opening steam.

When starting the compositor then closing it, the bug will be present on the next start. I tested with classic empty session, dbus session and uwsm from tty.
However it will only happen if I close it with a quit dispatch or a uwsm stop. If I use a loginctl terminate-user "", the bug is not here. Edit : nvm, the bug can be random even with terminate-user.

I think it would be good if anyone could confirm this.

Still need to test with other compositors as well.

**Comment by Maitreya93** [comment]
I'm still also facing this issue, after opening Steam initially the context items are placed somewhere around the monitor, but closing this window and then opening it from tray works. 
Screen resolution = 3440x1440@60 with Scale 1

**Comment by neoscaler** [comment]
Same here on fresh Arch niri installation. After closing the window and reopening from tray it works. But the first start is always broken.

**Comment by idoric** [comment]
I upgraded to v0.8 three days ago, and since then the problem has disappeared for me.

**Comment by sudoharun** [comment]
The issue is mostly gone for me, there is still one place that it's misplaced.

![Image](https://github.com/user-attachments/assets/0761706e-a65b-4465-b914-47dbcaaa4d65)

**Comment by crispy-caesus** [comment]
https://github.com/user-attachments/assets/ad8ef989-2649-4af7-93c6-521234fec7f1

Is this possibly related?
When I open steam and then xeyes on the same workspace, I can get the hover menus from steam in xeyes.

xw-s version: 0.8.0
compositor: niri 25.11
os: Chimera Linux

I sadly don't have the time right now to make a new issue and test on the latest commit.

**Comment by captainzonks** [comment]
<img width="441" height="281" alt="Image" src="https://github.com/user-attachments/assets/6fd4c9e7-9853-4ada-8a71-3817e498826f" />
<img width="441" height="281" alt="Image" src="https://github.com/user-attachments/assets/812d8b7c-efcc-48fb-8efb-316210785e74" />

I'd like to add something to this conversation: if Steam is launched in fullscreen in niri, the top menus have a gap rendered, which causes the dropdown to be inaccessible when the mouse passes over the lower menu of Store, Library, Community, Username.

This doesn't occur if Steam is in a window. These rules fix the menu issue for anyone encountering this, and handle the "launching" popup, as well as others, so that the main Steam app itself is isolated and handled:

```
// Steam main window — prevent fullscreen so menus work
window-rule {
    match app-id=r#"^steam$"# title=r#"^Steam$"#
    open-fullscreen false
}

// Steam popups as floating (news, updates, dialogs)
window-rule {
    match app-id=r#"^steam$"# title=r#"^(Steam - News|Special Offers|notificationtoasts)"#
    open-floating true
}
```

BONUS FIX (for those who need it):

Also, want to add as an additional Steam fix I had to do, if anyone is having laggy, choppy issues with Big Picture Mode where it kinda runs at like a terrible 5 fps, it's because it's not utilizing GPU at all. Add this to your env vars for niri:

```
    // Steam — override CEF's GPU blacklist (prevents --disable-gpu software fallback)
    STEAM_CEF_EXTRA_ARGS "--ignore-gpu-blocklist --enable-gpu-rasterization"
```

And you'll now have a smooth experience with Big Picture.

**Comment by bczhc** [comment]
Hmm just randomly searched and reached here. From what I could recall, all the issues in this thread, have never ever been encountered by me. I'm also on niri (started using niri since March 19; tested using both 25.11/git) + xwayland-satellite latest release from the Arch official repo.

<img width="250" alt="Image" src="https://github.com/user-attachments/assets/374d8c8b-eca3-4230-8ea4-cb3fc6def6e3" />
<img width="250" height="" alt="Image" src="https://github.com/user-attachments/assets/a5997bc5-32a0-4a26-bb56-3dec3a8b01b4" />
<img width="400" height="" alt="Image" src="https://github.com/user-attachments/assets/008f0d72-720e-4a74-966f-1b4f80041dfe" />

Initial steam run above. Not "close then open again via tray-icon". My niri scaling is 1.333333333333.

**Comment by gouwazi** [comment]
I can reproduce a related input issue with Steam under niri and xwayland-satellite.

### Environment

- Distribution: Gentoo
- niri: 26.04 (8ed0da4)
- xwayland-satellite: 0.8.1
- Xwayland: 24.1.13
- GPU: NVIDIA GeForce RTX 4060 Ti
- NVIDIA driver: 595.84
- Steam: Flatpak, stable, 1.0.0.85
- Display: 3840x2160 at 60 Hz
- niri logical size: 1920x1080
- Scale: 2

### Symptoms

After leaving Steam running for a long time, parts of the main Steam window stop accepting mouse clicks.

In my case:

- The top `View` and `Friends` menus can still be clicked.
- Hovering over `Store`, `Library`, etc. still opens their hover menus.
- Clicking those navigation items does nothing.
- The main page below the navigation bar stops responding to clicks completely.
- Other applications continue receiving mouse input normally.

Closing only the main Steam window and reopening it from the tray immediately fixes the issue. Steam itself does not need to be restarted.

This workaround has now been successfully verified.

### Observations

Steam had been running for approximately 24 hours when the issue was inspected.

The Steam X11 main window had the following size:

```text
"Steam": ("steamwebhelper" "steam") 3832x2064+0+0
```

The corresponding niri window size was:

```text
1916x1032
```

This is consistent with the output scale of 2.

The X11 window tree also contained multiple Steam CEF override-redirect popup windows, for example:

```text
("steamwebhelper" "steam")
Class: InputOutput
Override Redirect State: yes
```

There were around 11 such popup windows with different sizes and positions. They were unmapped when inspected.

Steam's logs contain repeated X11 errors around CEF popup/window handling:

```text
X error received. Request: SendEventRequest, Error: WindowError
Steam: An X Error occurred
X Error of failed request: BadAtom (invalid Atom parameter)
```

The CEF log has also previously recorded errors such as:

```text
eglMakeCurrent failed with error EGL_CONTEXT_LOST
GPU process exited unexpectedly
XGetWindowAttributes failed
```

`steamui_html.txt` shows multiple `PopupHTMLWindow` creations and several webhelper restarts during the same session.

### Additional information

Steam currently starts `steamwebhelper` with GPU acceleration disabled:

```text
--disable-gpu-compositing --disable-gpu
```

There was no OOM event, and mouse input continued to work in every other application.

The behavior appears to be related to Steam's CEF/X11 popup or pointer-grab state becoming inconsistent after a long-running session. Recreating only the main Steam window resets the state and restores clicking.

I am currently testing whether keeping Steam at half-screen width instead of nearly fullscreen changes the reproduction frequency. I can provide additional logs or run targeted diagnostics the next time it happens.

**Comment by gouwazi** [comment]
I reproduced the issue again while Steam was at approximately half-screen width, so it is not limited to fullscreen or nearly-fullscreen windows.

I captured both the broken state and the working state after applying the workaround.

### Broken state

The niri window had a logical size of approximately:

```text
1010x1028
```

The corresponding Steam X11 top-level window was:

```text
0x2000025 "Steam"
2020x2056
WM_CLASS = "steamwebhelper", "steam"
Map State: IsViewable
```

Steam had two relevant child input surfaces:

```text
0x1800013 2020x2056
0x1800017 2018x1771
```

Both had:

```text
Override Redirect State: yes
WM_WINDOW_ROLE = "popup"
_NET_WM_WINDOW_TYPE = _NET_WM_WINDOW_TYPE_NOTIFICATION
```

Both surfaces were selecting the expected input events:

```text
KeyPress
KeyRelease
ButtonPress
ButtonRelease
EnterWindow
LeaveWindow
PointerMotion
FocusChange
```

Despite this, the main page did not respond to mouse button presses. Some hover behavior and the top View/Friends menus continued working.

There was no OOM event and no Steam or main steamwebhelper restart.

### Recovery behavior

I closed only the Steam main window and reopened it from the tray. Clicking immediately started working again.

The important observation is that after recovery:

- The Steam X11 top-level window ID was still `0x2000025`.
- Its X11 PID was unchanged.
- The main `steamwebhelper` process was unchanged.
- The niri window ID changed from `168` to `220`.

Therefore, recovery did not require restarting Steam or its main CEF browser process. It happened when the same X11 top-level window was unmapped and mapped again, causing xwayland-satellite/niri to create a new Wayland-side window/surface.

This suggests that the problem may involve stale X11-to-Wayland input surface association or input routing state in the xwayland-satellite window lifecycle, rather than the Steam webpage or renderer becoming unresponsive.

The issue was noticed around 20 minutes after unlocking the niri session, although I cannot yet confirm that lock/unlock is the trigger.

**Comment by totalolage** [comment]
### Additional deterministic reproduction: Steam popups close immediately

I can reproduce a related variant consistently: Steam dropdown/context menus appear briefly, then close by themselves before they can be used. This happens on both the packaged `0.8.2` and current `main`. The same Steam build works correctly in a nested Labwc session using its native Xwayland implementation.

#### Environment

- Arch Linux, kernel `7.2.2-arch1-1`
- niri `26.04 (8ed0da4)`
- xwayland-satellite package `0.8.2-1`
- xwayland-satellite `main` at `78e4e01ea9920ba302459753e1492b60f0bdc201` (`v0.8.2-9-g78e4e01`)
- Xwayland `24.1.13-1`
- Steam package `1.0.0.87-3`, client build ID `1788291500`
- AMD Radeon 880M/890M (`amdgpu`)
- One internal output at position `0,0`, `2880x1920@120`
- Normally scale `1.5`; also reproduced with a clean Steam/Satellite start at scale `1`
- Niri `focus-follows-mouse` is not enabled

#### Steps to reproduce on current `main`

1. Build current xwayland-satellite `main`.
2. Start an isolated instance with `RUST_LOG=debug ./target/release/xwayland-satellite :1`.
3. Start Steam with `DISPLAY=:1 /usr/bin/steam`.
4. Open a top dropdown/hover menu or a library context menu.
5. The menu flashes open and closes almost immediately. This is reproducible across repeated attempts.

I repeated this with a fresh Satellite and Steam process after setting the output to scale `1`, not by changing scale while Steam was running. The result was the same.

#### Controls and attempted workarounds

- Reproduces on packaged xwayland-satellite `0.8.2-1`.
- Reproduces on current upstream commit `78e4e01`.
- Reproduces at scale `1.5`.
- Reproduces after a clean start at scale `1`, so it is not dependent on fractional scaling.
- `steam -forcedesktopscaling 1` does not help.
- `STEAM_FORCE_DESKTOPUI_SCALING=1.5 steam` does not help.
- Closing only Steam's initial main window and reopening it does not help here.
- Steam's `EnableContextMenuBlurDelay3=true` compatibility option only delays the close slightly.
- The main Steam window is not fullscreen.
- During an earlier packaged-version capture, `niri msg event-stream` showed no Niri toplevel focus/window event at the moment of failure.
- **Control:** launching the same Steam installation inside nested Labwc (`labwc --startup /usr/bin/steam`) makes the menus stay open and work normally.

#### Relevant log behavior

At scale `1.5`, Satellite recognizes the window as an override-redirect `_NET_WM_WINDOW_TYPE_POPUP_MENU`, creates and focuses an `xdg_popup`, reports the pointer entering it, then reports a leave/re-entry to the parent almost immediately. Steam subsequently unmaps the popup:

```text
08:51:33.896 window_role_heuristics > Window { res_id: 31457425 } set to Popup ... override_redirect: true ... window_types: ["_NET_WM_WINDOW_TYPE_POPUP_MENU"] ... wm_class: Some("steam")
08:51:33.896 xwayland_satellite::server > creating popup ... WindowDims { x: 359, y: 99, width: 198, height: 247 } ... (scale: 1.5)
08:51:33.897 xwayland_satellite::server > focusing popup Window { res_id: 31457425 }
08:51:33.904 xwayland_satellite::server::event > pointer entering wl_surface@38[0] (394299 1.5)
08:51:33.919 xwayland_satellite::server::event > leaving surface (wl_surface@78)
08:51:33.919 xwayland_satellite::server::event > pointer entering wl_surface@29[0] (394309 1.5)
08:51:34.081 xwayland_satellite::server > unmapping Window { res_id: 31457425 }
```

In the clean scale-`1` capture, the popup is likewise classified, created, focused, and then unmapped about 180 ms later:

```text
09:17:03.751 xwayland_satellite::server > Using new scale 1
09:29:29.776 window_role_heuristics > Window { res_id: 31457439 } set to Popup ... override_redirect: true ... window_types: ["_NET_WM_WINDOW_TYPE_POPUP_MENU"] ... wm_class: Some("steam")
09:29:29.777 xwayland_satellite::server > creating popup ... WindowDims { x: 119, y: 1828, width: 2, height: 1 } ... (scale: 1)
09:29:29.778 xwayland_satellite::server > focusing popup Window { res_id: 31457439 }
09:29:30.062 xwayland_satellite::server > unmapping Window { res_id: 31457439 }
```

Full debug logs for both captures (no clipboard contents or credentials):

https://gist.github.com/totalolage/abfa9a28c7cbf4e2a644fd7ed6d71933

The Labwc control makes this look specific to the rootless X11-to-Wayland popup/input path rather than a general Steam menu bug. I can run targeted patches or collect a Wayland protocol trace if that would help.
