### ISSUE TITLE
steamwebhelper core dumps and no longer boots after DPMS monitor power-off on Niri

### ISSUE THREAD

**Issue by wisheth** [Supreeeme/xwayland-satellite#239]
### Operating System

CachyOS

### Wayland Compositor

Niri

### Describe the issue.

Not having steamwebhelper active means that Steam is nothing but a tray icon and can't even boot games. I have to restart my system to get access to Steam after a power-off. Given the rest of the logs, I imagine this is not exclusive to Steam.

If it's relevant, I'm running on a modern Nvidia GPU.

The following log should contain everything that happens from about the time my monitor turns on to when I boot Steam. I imagine Steam isn't the only affected application, but it's a notable one.
[xwayland-satellite.log](https://github.com/user-attachments/files/22451114/xwayland-satellite.log)

EDIT: This post initially spoke on suspending instead of the DPMS power-off I didn't realize was actually going on. On first impression, suspending seems to work fine, oddly enough, and I think that's gonna be my workaround in the short-term, as my computer's had issues with just turning off the monitor at times that I've never understood how to fix. I do want to see if I can make this work, so I'll keep updating here.

### Steps to reproduce

Restart the system and suspend automatically using Swayidle with Swaylock as instructed in the Niri guides, then launch Steam after waking up and unlocking the system. No window should pop up, only a tray icon that is the only indicator Steam is on

### Please confirm you have reproduced this on the latest commit.

- [x] I have reproduced this on the latest commit

**Comment by Supreeeme** [comment]
- steamwebhelper tends to segfault for a myriad number of reasons, I'm not positive this can be blamed on satellite
- I am able to suspend and wake on niri with steam open without issue

I would suggest you try this on another compositor first to see if it's satellite or steam that's the issue here.

**Comment by wisheth** [comment]
Seems to be an issue with `niri msg action power-off-monitors`, actually. I don't know why I pinned this on a suspend I thought was happening, but wasn't really. I'll make changes to the main post, and given the nature of the bug, I'll toss something on the Niri issue board as well.

**Comment by noisegrrrl** [comment]
I am having the same issue, with both steam and vesktop and I am unable to restart them until I first kill xwayland-satellite.
The core dump don't happen immediately after turning off the screen but a few minutes after.

I can provide more information if you tell me what to look for/where/how.

**Comment by noisegrrrl** [comment]
Also I'm running on an AMD GPU unlike @wisheth but I am also on CachyOS.

**Comment by Supreeeme** [comment]
- What is the exact sequence of steps that causes steam to core dump?
- What is your monitor configuration?
- Post the satellite log with `RUST_LOG=debug` set - if you launch satellite from a terminal, the log is printed to it.

**Comment by Fingel** [comment]
I thought I was having the same issue - and maybe it's related. But in my case attempting to launch Steam would crash not only Steam but every other application using xwayland-satellite (discord, slack, etc). For anyone else that finds this issue, try:

`wl-copy --clear` 

And see if you can then launch Steam. This is #260. Rebooting/restarting the session does functionally the same thing which might be why it seems like it's related to DKMS or Swayidle or Swaylock.

**Comment by noisegrrrl** [comment]
Haven't had time to check that further but here's one thing I noticed:

It doesn't matter if steam was started before the computer idling or not, trying to start it after the screen was turned off and the computer went to idle prevents steam from starting until you kill xwayland-satellite

**Comment by abcfy2** [comment]
I can reproduce this on CachyOS with niri, but with WeChat (a native Linux X11 application) instead of Steam.

**Environment**

- OS: CachyOS Linux
- Kernel: 6.19.9-1-cachyos
- niri: 25.11 (b35bcae)
- xwayland-satellite: 0.8.1-1
- Shell: DMS (Dank Material Shell, built on quickshell)
- Affected application: WeChat (`/opt/wechat/wechat`, native Linux build)

**Observed behavior**

After the monitor is powered off via DPMS (configured through DMS idle/sleep settings), WeChat's tray icon disappears upon wake. The WeChat process has exited, confirmed by `systemd-coredump`.

**What the logs show**

Today alone, xwayland-satellite exited with status 101 four times, each followed immediately by a WeChat core dump:

```
Mar 21 08:58:40 niri[1286]: DEBUG niri::utils::xwayland::satellite: connection to X11 abstract socket; spawning xwayland-satellite

Mar 21 11:42:59 niri[1286]: WARN  niri::utils::xwayland::satellite: xwayland-satellite exited with: exit status: 101
Mar 21 11:42:59 niri[1286]: DEBUG niri::utils::xwayland::satellite: connection to X11 abstract socket; spawning xwayland-satellite
Mar 21 11:43:01 systemd-coredump: Process 2448 (wechat) of user 1000 dumped core.

Mar 21 12:05:12 niri[1286]: WARN  niri::utils::xwayland::satellite: xwayland-satellite exited with: exit status: 101
Mar 21 12:06:32 niri[1286]: DEBUG niri::utils::xwayland::satellite: connection to X11 abstract socket; spawning xwayland-satellite

Mar 21 12:23:12 niri[1286]: WARN  niri::utils::xwayland::satellite: xwayland-satellite exited with: exit status: 101
Mar 21 12:23:15 systemd-coredump: Process (wechat) of user 1000 dumped core.
Mar 21 12:27:40 niri[1286]: DEBUG niri::utils::xwayland::satellite: connection to X11 abstract socket; spawning xwayland-satellite

Mar 21 16:50:16 niri[1286]: WARN  niri::utils::xwayland::satellite: xwayland-satellite exited with: exit status: 101
Mar 21 16:50:16 niri[1286]: DEBUG niri::utils::xwayland::satellite: connection to X11 abstract socket; spawning xwayland-satellite
Mar 21 16:50:19 systemd-coredump: Process 116133 (wechat) of user 1000 dumped core.
```

niri restarts xwayland-satellite automatically after each exit. The pattern is consistent: xwayland-satellite exits with status 101, niri spawns a new instance within milliseconds, and the X11 application that was connected to the previous instance core dumps shortly after.

Not all xwayland-satellite exits are followed by a WeChat core dump (e.g. the 12:05 exit has no corresponding dump), which may suggest the crash depends on whether WeChat was actively using the Xwayland connection at that moment.

**Comment by kermeat** [comment]
When I turn off the monitor, this happens:
```
thread 'main' (167504) panicked at src/server/mod.rs:703:52:
called Option::unwrap() on a None value
```
UPDATE: probably fixed by this commits https://github.com/Supreeeme/xwayland-satellite/commit/e6dd3c05c098aef4e6a31fa95c04f129e9b52618 https://github.com/Supreeeme/xwayland-satellite/commit/10f985b84cdbcc3bbf35b3e7e43d1b2a84fa9ce2

**Comment by kermeat** [comment]
Tried master(a879e5e), all working as expected now.

**Comment by ArikRahman** [comment]
I can reproduce the issue with the same specs as @abcfy2 except using NIxOS (with cachy kernel). I am seeing a lot of closed issues like #387 claiming the issue was fixed but I am still getting the issue a few months later.

**Comment by abcfy2** [comment]
> I can reproduce the issue with the same specs as [@abcfy2](https://github.com/abcfy2) except using NIxOS (with cachy kernel). I am seeing a lot of closed issues like [#387](https://github.com/Supreeeme/xwayland-satellite/pull/387) claiming the issue was fixed but I am still getting the issue a few months later.

Because the release version not contains this bug fix. I use AUR xwayland-satellite-git: https://aur.archlinux.org/packages/xwayland-satellite-git , and it works.

**Comment by ArikRahman** [comment]
Okay, I will track upstream master with flake.nix
