### ISSUE TITLE
Fcitx5 Scaling and Rendering Issues Under Niri (Scale=2) with some Apps

### ISSUE THREAD

**Issue by HenghengBaoding** [Supreeeme/xwayland-satellite#301]
### Operating System

CachyOS

### Wayland Compositor

Niri

### Describe the issue.

My desktop environment is CachyOS + Niri, and my Niri monitor scale is set to 2. I currently have two issues:

1. Fcitx5 is not affected by the global scale = 2 setting in WeChat, DingTalk, and Feishu. These three applications display correctly, but the Fcitx5 candidate window remains at 1× scale and appears very small.

2. When using an Fcitx5 theme with rounded corners, there are four black areas visible outside the rounded corners.

<img width="998" height="186" alt="Image" src="https://github.com/user-attachments/assets/ed198c5f-327a-4f43-a9d7-9ce14eb19e4c" />

### Please confirm you have reproduced this on the latest commit.

- [x] I have reproduced this on the latest commit

**Comment by busyoGG** [comment]
> Fcitx5 is not affected by the global scale = 2 setting in WeChat, DingTalk, and Feishu. These three applications display correctly, but the Fcitx5 candidate window remains at 1× scale and appears very small.

Under Xwayland, Fcitx5 uses a fixed DPI and does not perform any scaling calculations.

**Comment by olivezane** [comment]
> > Fcitx5 is not affected by the global scale = 2 setting in WeChat, DingTalk, and Feishu. These three applications display correctly, but the Fcitx5 candidate window remains at 1× scale and appears very small.在微信、钉钉和飞书中，Fcitx5 未受全局缩放比例=2 设置的影响。这三个应用程序显示正常，但 Fcitx5 的候选词窗口仍保持 1× 缩放比例，显得非常小。
> 
> Under Xwayland, Fcitx5 uses a fixed DPI and does not perform any scaling calculations.在 Xwayland 环境下，Fcitx5 使用固定的 DPI 设置，不执行任何缩放计算。

How can I set up a fixed DPI for Fcitx5 under Xwayland?

**Comment by busyoGG** [comment]
> How can I set up a fixed DPI for Fcitx5 under Xwayland?

Cannot be modified. It only relates to Xwayland's logical resolution and the physical size of the monitor.

**Comment by Supreeeme** [comment]
Based on this from the fcitx5 source: https://github.com/fcitx/fcitx5/blob/d0928cedba8632428ad8268b0ad21705676bfb14/src/ui/classic/xcbui.cpp#L99

It seems it reads from the X11 Resource Manager stuff, which satellite currently does not handle. I'll add support for it and we can see if it fixes it.

**Comment by HenghengBaoding** [comment]
> Yes, the fcitx5 DPI issue can be solved in two steps

- ```
  vim ~/.Xresources
  ----------------------
  Xft.dpi: 192
  Xft.autohint: 0
  Xft.lcdfilter: lcddefault
  Xft.hintstyle: hintfull
  Xft.hinting: 1
  Xft.antialias: 1
  Xft.rgba: rgb
  ```

- ```
  echo 'spawn-at-startup "xrdb" "-merge" "/home/xxxx/.Xresources"' >> ~/.config/niri/config.kdl
  ```

> However, if the fcitx5 theme has rounded corners, applications like WeChat and DingTalk still show four black corners. And when typing, the fcitx5 candidate window often feels shaky and somewhat delayed. It frequently happens that certain letters jump out of the candidate window. For example: I expect “shuru” to be inside the candidate window, but in reality it becomes “shru”, where “u” jumps directly into the text. Fcitx5 works smoothly everywhere else except in these applications. Thank you for your contribution to xwayland-satellite, and I hope you can make it work even better. Thank  you. @Supreeeme

**Comment by GoodbyeNJN** [comment]
> 2. When using an Fcitx5 theme with rounded corners, there are four black areas visible outside the rounded corners.

This issue has been fixed by https://github.com/Supreeeme/xwayland-satellite/pull/381

**Comment by smaxad47** [comment]
> > 2. When using an Fcitx5 theme with rounded corners, there are four black areas visible outside the rounded corners.
> 
> This issue has been fixed by [#381](https://github.com/Supreeeme/xwayland-satellite/pull/381)

Thanks for the heads up, but I am still experiencing the exact same issue.
Environment: CachyOS + Niri + DMS
Under WeChat, the Fcitx5 window still fails to render the transparent layer (leaving the black areas visible outside the rounded corners).

<img width="490" height="139" alt="Image" src="https://github.com/user-attachments/assets/c667c1fd-0128-463d-8f45-e804c7f4e1a1" />

**Comment by GoodbyeNJN** [comment]
> Thanks for the heads up, but I am still experiencing the exact same issue. Environment: CachyOS + Niri + DMS Under WeChat, the Fcitx5 window still fails to render the transparent layer (leaving the black areas visible outside the rounded corners).
> <img alt="Image" width="490" height="139" src="https://private-user-images.githubusercontent.com/12371186/628347335-c667c1fd-0128-463d-8f45-e804c7f4e1a1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODUzMjMwNDksIm5iZiI6MTc4NTMyMjc0OSwicGF0aCI6Ii8xMjM3MTE4Ni82MjgzNDczMzUtYzY2N2MxZmQtMDEyOC00NjNkLThmNDUtZTgwNGM3ZjRlMWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNzI5VDEwNTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMmU0Zjg5MTk0NjlmMzVjZTA1ODQ4NjA4MWNiMDM3ZjZmNjg4OWRhMzBlYTZkMTQ1NDdjZTA3ZDQ2ZmM4NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.Y61sHIY-pMb28FCPZxsLjD8UiTjxBq_acaLM5vfjSJI">

Could you provide the Fcitx5 skin you’re using? I plan to try it in my environment. If this issue can be reproduced, we’ll need to further diagnose the problem.

**Comment by smaxad47** [comment]
> > Thanks for the heads up, but I am still experiencing the exact same issue. Environment: CachyOS + Niri + DMS Under WeChat, the Fcitx5 window still fails to render the transparent layer (leaving the black areas visible outside the rounded corners).
> > <img alt="Image" width="490" height="139" src="https://private-user-images.githubusercontent.com/12371186/628347335-c667c1fd-0128-463d-8f45-e804c7f4e1a1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODUzMjMwNDksIm5iZiI6MTc4NTMyMjc0OSwicGF0aCI6Ii8xMjM3MTE4Ni82MjgzNDczMzUtYzY2N2MxZmQtMDEyOC00NjNkLThmNDUtZTgwNGM3ZjRlMWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNzI5VDEwNTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMmU0Zjg5MTk0NjlmMzVjZTA1ODQ4NjA4MWNiMDM3ZjZmNjg4OWRhMzBlYTZkMTQ1NDdjZTA3ZDQ2ZmM4NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.Y61sHIY-pMb28FCPZxsLjD8UiTjxBq_acaLM5vfjSJI">
> 
> Could you provide the Fcitx5 skin you’re using? I plan to try it in my environment. If this issue can be reproduced, we’ll need to further diagnose the problem.

Thank you for looking into this!
I am using the fcitx5-theme-pt-cute-light skin. You can find it here: 
https://github.com/Passthem-desu/fcitx5-theme-pt-cute-light

**Comment by GoodbyeNJN** [comment]
> Thank you for looking into this! I am using the fcitx5-theme-pt-cute-light skin. You can find it here: https://github.com/Passthem-desu/fcitx5-theme-pt-cute-light

I conducted a quick test, and the issue didn’t occur this time. Perhaps our Fcitx5 settings are different. Could you please share your Fcitx5 settings?

**Comment by smaxad47** [comment]
> > Thank you for looking into this! I am using the fcitx5-theme-pt-cute-light skin. You can find it here: https://github.com/Passthem-desu/fcitx5-theme-pt-cute-light
> 
> I conducted a quick test, and the issue didn’t occur this time. Perhaps our Fcitx5 settings are different. Could you please share your Fcitx5 settings?

My apologies for taking up your time! 

I double-checked my environment and realized that updating `xwayland-satellite` to 0.8.2 fixed the problem entirely. It was a mistake on my end for not ensuring everything was fully up to date.

Thank you again for your time and efforts!
