### ISSUE TITLE
If the app absolute position is outside physical screen, pointer input is not working

### ISSUE THREAD

**Issue by KosmX** [Supreeeme/xwayland-satellite#46]
For example if the screen is at 1000x0 (infinite size) and satellite reports a window position of 0x0, XWayland will **always** report a pointer position inside the physical screen (X >= 1000)

possible solutions i think:
- lie to XWayland, report a massive display from 0x0 with size including the whole setup
- move window inside physical screen (i don't know if wayland compositors provide an absolute window position)

I might try to do something about this.
This issue may be the same as #15

**Comment by Supreeeme** [comment]
This should have already been fixed by https://github.com/Supreeeme/xwayland-satellite/commit/d3a46b7c8a8abd339eca406d4f29cc6093e9a9f2

**Comment by KosmX** [comment]
It is not fixed on main branch as of writing this.
- arch
- Hyprland noX  (because if XWayland in Hyprland dies, it can kill the whole compositor)

**Comment by Supreeeme** [comment]
Finally got around to looking at this - it seems that satellite utilizes the wl_output positioning but Hyprland only updates the xdg_output positioning, which is fair given that it seems like xdg_output is supposed to be preferred to wl_output anyway, and Xwayland also acts as such. Shouldn't be too hard to fix.
